export const options = {
  brands: [
    "Rolex",
    "Omega",
    "Seiko",
    "Casio",
    "Timex",
    "Citizen",
    "Grand Seiko",
    "Patek Philippe",
    "Cartier",
    "Tag Heuer",
  ],
  models: [
    "Submariner",
    "Speedmaster",
    "Prospex",
    "G-Shock",
    "Weekender",
    "Eco-Drive",
    "Spring Drive",
    "Nautilus",
    "Santos",
    "Carrera",
  ],
  caseSizes: ["40mm", "42mm", "43mm", "46mm", "38mm"],
  caseShape: ["گرد", "غواصی", "گرند سیکو", "مربع"],
  caseMaterials: ["فولاد ضد زنگ", "رزین", "تمساح", "کروکودیل"],
  caseColors: ["نقره‌ای", "مشکی", "طلای رز", "فولادی"],
  bandMaterials: ["اویستر استیل", "چرم", "فولاد ضد زنگ", "تمساح", "کروکودیل"],
  bandColors: ["مشکی", "قهوه‌ای", "نقره‌ای"],
  dialColors: ["مشکی", "سفید", "آبی"],
  movements: ["اتوماتیک", "کوارتز", "اسپرینگ درایو"],
  waterResistance: [
    "1 اتمسفر",
    "2 اتمسفر",
    "3 اتمسفر",
    "4 اتمسفر",
    "5 اتمسفر",
    "6 اتمسفر",
    "7 اتمسفر",
    "8 اتمسفر",
    "9 اتمسفر",
    "10 اتمسفر",
  ],
  others: ["تقویم", "کرونومتر", "نیروی خورشیدی"],
};
