import productImage from "@/public/images/sample.png";
import productImage_1 from "@/public/images/sample_1.jpg";

export const products = [
  {
    id: 1,
    title: "Seiko model",
    desc: "some short desc",
    longDesc: "lorm ipsum",
    imgSrc: productImage,
    images: [productImage_1],
    price: 250000,
  },
  {
    id: 2,
    title: "Seiko model",
    desc: "some short desc",
    longDesc: "lorm ipsum",
    imgSrc: productImage,
    images: [productImage_1, productImage_1, productImage_1, productImage],
    price: 250000,
  },
  {
    id: 3,
    title: "Seiko model",
    desc: "some short desc",
    longDesc: "lorm ipsum",
    imgSrc: productImage,
    images: [productImage_1, productImage_1, productImage_1, productImage],
    price: 250000,
  },
  {
    id: 4,
    title: "Seiko model",
    desc: "some short desc",
    longDesc: "lorm ipsum",
    imgSrc: productImage,
    images: [productImage_1, productImage_1, productImage_1, productImage],
    price: 250000,
  },
  {
    id: 5,
    title: "Seiko model",
    desc: "some short desc",
    longDesc: "lorm ipsum",
    imgSrc: productImage,
    images: [productImage_1, productImage_1, productImage_1, productImage],
    price: 250000,
  },
  {
    id: 6,
    title: "Seiko model",
    desc: "some short desc",
    longDesc: "lorm ipsum",
    imgSrc: productImage,
    images: [productImage_1, productImage_1, productImage_1, productImage],
    price: 250000,
  },
  {
    id: 7,
    title: "Seiko model",
    desc: "some short desc",
    longDesc: "lorm ipsum",
    imgSrc: productImage,
    images: [productImage_1, productImage_1, productImage_1, productImage],
    price: 250000,
  },
  {
    id: 8,
    title: "Seiko model",
    desc: "some short desc",
    longDesc: "lorm ipsum",
    imgSrc: productImage_1,
    images: [productImage, productImage, productImage, productImage_1],
    price: 250000,
  },
  {
    id: 9,
    title: "Seiko model",
    desc: "some short desc",
    longDesc: "lorm ipsum",
    imgSrc: productImage_1,
    images: [productImage, productImage, productImage, productImage_1],
    price: 250000,
  },
  {
    id: 10,
    title: "Seiko model",
    desc: "some short desc",
    longDesc: "lorm ipsum",
    imgSrc: productImage_1,
    images: [productImage, productImage, productImage, productImage_1],
    price: 250000,
  },
  {
    id: 11,
    title: "Seiko model",
    desc: "some short desc",
    longDesc: "lorm ipsum",
    imgSrc: productImage_1,
    images: [productImage, productImage, productImage, productImage_1],
    price: 250000,
  },
  {
    id: 12,
    title: "Seiko model",
    desc: "some short desc",
    longDesc: "lorm ipsum",
    imgSrc: productImage_1,
    images: [productImage, productImage, productImage, productImage_1],
    price: 250000,
  },
  {
    id: 13,
    title: "Seiko model",
    desc: "some short desc",
    longDesc: "lorm ipsum",
    imgSrc: productImage_1,
    images: [productImage, productImage, productImage, productImage_1],
    price: 250000,
  },
  {
    id: 14,
    title: "Seiko model",
    desc: "some short desc",
    longDesc: "lorm ipsum",
    imgSrc: productImage_1,
    images: [productImage, productImage, productImage, productImage_1],
    price: 250000,
  },
  {
    id: 15,
    title: "Seiko model",
    desc: "some short desc",
    longDesc: "lorm ipsum",
    imgSrc: productImage_1,
    images: [productImage, productImage, productImage, productImage_1],
    price: 250000,
  },
];
